inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/{bundle,rails,rake,setup,update,yarn}'
  SuggestExtensions: false
  NewCops: enable

# 各種スタイル設定
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/CommentedKeyword:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  EnforcedStyle: annotated
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/Documentation:
  Enabled: false

# レイアウト設定
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 140
  Exclude:
    - 'app/system_admin/**/*'
    - 'app/libs/system_admins/components/**/*'
  AllowedPatterns:
    - "'.+'"
    - '".+"'
    - '#.+'
    - '/.+/'
    - '([A-Z][A-Za-z\d]+::){2,}[A-Z]'
    - '([A-Z]+_){4,}[A-Z]'
    - '\s+(has_one|has_many|belongs_to|validate|validates|delegate)\s+:.+'
    - '\s+(indexes)\s+:.+'
    - '(^|\s+)def [^\(]+\(.+\)'

# Lint設定
Lint/MissingSuper:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space
Lint/SuppressedException:
  Exclude:
    - 'spec/**/*'

# メトリクス設定
Metrics/AbcSize:
  Exclude:
    - 'lib/tasks/helpers/test_data_helper.rb'
  Max: 50
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'app/libs/admins/components/**/*'
    - 'spec/**/*'
    - 'lib/tasks/helpers/test_data_helper.rb'
    - '*.gemspec'
    - 'config/routes.rb'
  AllowedMethods:
    - 'configure'
    - 'class_eval'
    - 'extended'
    - 'helpers'
    - 'included'
    - 'instance_eval'
    - 'namespace'
    - 'resource'
    - 'resources'
    - 'route_param'
    - 'transaction'
    - 'class_methods'
Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'app/api/*_apis/*/apis/*.rb'
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Exclude:
    - 'lib/tasks/helpers/test_data_helper.rb'
  Max: 50
Metrics/ModuleLength:
  Exclude:
    - 'lib/tasks/helpers/test_data_helper.rb'
  CountAsOne:
    - array
    - hash
    - heredoc
Metrics/ParameterLists:
  CountKeywordArgs: false

# 命名設定
Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - id
    - ip
    - to

# RSpec設定
RSpec/AnyInstance:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/SpecFilePathSuffix:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  EnforcedStyle: described_class
RSpec/ExampleLength:
  Enabled: false
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/ImplicitExpect:
  EnforcedStyle: is_expected
RSpec/ImplicitSubject:
  EnforcedStyle: disallow
RSpec/IteratedExpectation:
  Enabled: false
RSpec/InstanceVariable:
  AssignmentOnly: true
RSpec/MessageChain:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 20
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 8
RSpec/LetSetup:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false

# 新しいコップの設定
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Metrics/CollectionLiteralLength:
  Enabled: true
Naming/BlockForwarding:
  Enabled: true
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EmptyHeredoc:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/OperatorMethodCall:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/SuperArguments:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true
